name: E2E

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  e2e:
    # Don’t run secrets on forks; only on PRs from this repository or direct pushes
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false
    runs-on: ubuntu-latest
    timeout-minutes: 40
    env:
      # Option A: SFDX Auth URL (simple)
      SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
      # Option B: JWT (connected app)
      SF_CONSUMER_KEY: ${{ secrets.SF_CONSUMER_KEY }}
      SF_JWT_KEY: ${{ secrets.SF_JWT_KEY }}
      SF_USERNAME: ${{ secrets.SF_USERNAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli

      - name: Auth Dev Hub (JWT or SFDX URL)
        shell: bash
        run: |
          set -euo pipefail
          if [[ -n "${SF_CONSUMER_KEY:-}" && -n "${SF_JWT_KEY:-}" && -n "${SF_USERNAME:-}" ]]; then
            echo "Using JWT auth" >&2
            echo "$SF_JWT_KEY" > server.key
            sf org login jwt \
              --client-id "$SF_CONSUMER_KEY" \
              --jwt-key-file server.key \
              --username "$SF_USERNAME" \
              -a DevHub -s
          elif [[ -n "${SFDX_AUTH_URL:-}" ]]; then
            echo "Using SFDX auth URL" >&2
            echo "$SFDX_AUTH_URL" > sfdx-url.txt
            sf org login sfdx-url --sfdx-url-file sfdx-url.txt -a DevHub -s
          else
            echo "No auth secrets set. Provide SFDX_AUTH_URL or JWT secrets (SF_CONSUMER_KEY, SF_JWT_KEY, SF_USERNAME)." >&2
            exit 1
          fi

      - name: Build curated blueprint library
        run: node scripts/build-blueprint-library.js

      - name: Run E2E
        run: ./scripts/e2e.sh dynamicAction

      - name: Upload .tmp artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-tmp
          path: .tmp
          if-no-files-found: ignore

      - name: Delete scratch org
        if: always()
        run: sf org delete scratch -o dynamicAction -p
